### PR TITLE
Character names

### PR DESCRIPTION
**Pull request by kajo404**
Now provides a function to get all character names in JSON object in the following format:

```
[ { name: 'Addam' },
  { name: 'Alaric of Eysen' },
  { name: 'Alia' },
  { name: 'Alyce' },
  { name: 'Armen' },
  { name: 'Arneld' },
  { name: 'Barre' },
  { name: 'Beldecar' }]
```

### CODE REVIEW

**Comment by sacdallago** [comment]
Why don't you use A's APIs for this? Remember: work smart, work [lean](http://hackerchick.com/agile-vs-lean-yeah-yeah-whats-the-difference)

**Comment by vanp33** [comment]
can we get just the string array without "name": ['Alia'.'Alyce',...]

**Comment by sacdallago** [comment]
Use a [map function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

**Comment by Logarythms** [comment]
@sacdallago Afaik this uses Projekt A's API

**Comment by kajo404** [comment]
@sacdallago This feature calls a GET request on A's database to get all character. The function then only uses the names as the database provides a lot of other information as well. What would the benefit be of using a map function over an array? The for loop basically does the same thing, as we only look at every single entry and copy the name to a new json object.
The for loop even seems to be [faster](https://jsperf.com/array-map-vs-for-loop-1) ;) 

@vanp33 The json array can be easily iterated(with a for loop or the map function) to get the names and also allows future extension without impacting existing code. If a String array would be used future additions might conflict with existing code. json[0].name will always provide the name of the first character, even if you add other information such as episode of death, house, or faction.

**Comment by sacdallago** [comment]
Oh. How stupid of me! Sorry :P was reading the code, but not carefully enough apparently :P :P

**Comment by kajo404** [comment]
Shouldn't you be listening to the talk? ;)

Christian Dallago notifications@github.com schrieb am Mo., 14. März 2016
11:34:

**Comment by sacdallago** [comment]
I'm a multitasker :sunglasses:

**Pull request merged**
